"""\
Integrate bioimage analysis with Bio-Formats and Hadoop.
"""

import os
import glob
from distutils.command.build import build as BaseBuild
from distutils.errors import DistutilsSetupError
from distutils.core import setup


NAME = "pyfeatures"
DESCRIPTION = __doc__
URL = "https://github.com/simleo/pydoop-features.git"
CLASSIFIERS = [
    "Programming Language :: Python",
    "Topic :: Scientific/Engineering :: Bio-Informatics",
    "Intended Audience :: Science/Research",
]


def write_schema_module():
    with open(os.path.join("pyfeatures", "schema.py"), "w") as fo:
        fo.write("# GENERATED BY setup.py\n")
        fnames = glob.glob(os.path.join("src", "main", "avro", "*.avsc"))
        if not fnames:
            raise DistutilsSetupError(
                "Avro schema files not found! Build the Maven project first"
            )
        for fn in fnames:
            name = os.path.basename(os.path.splitext(fn)[0])
            with open(fn) as f:
                fo.write('\n%s = """\\\n%s"""\n' % (name, f.read()))


class Build(BaseBuild):

    def run(self):
        write_schema_module()
        BaseBuild.run(self)


setup(
    name=NAME,
    description=DESCRIPTION,
    url=URL,
    classifiers=CLASSIFIERS,
    packages=[
        "pyfeatures",
        "pyfeatures.app",
    ],
    scripts=["scripts/pyfeatures"],
    cmdclass={"build": Build}
)
