#!/bin/bash

die() {
    echo "$1" 1>&2
    exit 1
}

[ -z "${SGE_TASK_ID}" ] && die "ERROR: run via qsub"

. "${HOME}"/.bashrc
env

echo -en "START SERIALIZE " && date +%s
pyfeatures serialize "$@"
echo -en "STOP SERIALIZE " && date +%s
