#!/usr/bin/env python

import sys
import os
import argparse

from avro.datafile import DataFileReader
from avro.io import DatumReader
import numpy as np


BASEDIR = os.path.dirname(os.path.abspath(__file__))
AVRODIR = os.path.join(BASEDIR, os.path.pardir, 'src', 'main', 'avro')
SCHEMA_FN = os.path.join(AVRODIR, 'bioimgplane.avsc')


def make_parser():
    parser = argparse.ArgumentParser()
    parser.add_argument('img_file', metavar='IMG_FILE')
    parser.add_argument('-s', '--schema', metavar='FILE', default=SCHEMA_FN,
                        help='avro schema file')
    return parser


# no schema needed for deserialization
def iterplanes(img_file):
    with open(img_file, 'rb') as f:
        reader = DataFileReader(f, DatumReader())
        for plane in reader:
            yield plane


# FIXME: add endianness info to avro record
def build_array(plane):
    dtype = getattr(np, plane['pixel_type'].lower())
    a = np.fromstring(plane['data'], dtype=dtype)
    return a.reshape(plane['size_x'], plane['size_y'])


def main(argv):
    parser = make_parser()
    args = parser.parse_args(argv)
    for p in iterplanes(args.img_file):
        print '%s[%d] [%d, %d, %d]' % (
            p['name'], p['index'], p['index_z'], p['index_c'], p['index_t'],
        )
        a = build_array(p)
        out_fn = '%s-z%04d-c%04d-t%04d.npy' % (
            p['name'], p['index_z'], p['index_c'], p['index_t']
        )
        np.save(out_fn, a)


if __name__ == '__main__':
    main(sys.argv[1:])
