#!/usr/bin/env python

# BEGIN_COPYRIGHT
#
# Copyright (C) 2014-2015 CRS4.
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may not
# use this file except in compliance with the License. You may obtain a copy
# of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.
#
# END_COPYRIGHT

import sys
import os
import warnings
import argparse
from contextlib import closing

try:
    from pyavroc import AvroFileReader
except ImportError:
    from pyavroc_emu import AvroFileReader
    warnings.warn("pyavroc not found, using standard avro lib\n")
import numpy as np
from libtiff import TIFF

from bioimg import BioImgPlane


def make_parser():
    parser = argparse.ArgumentParser()
    parser.add_argument('avro_file', metavar='AVRO_FILE')
    parser.add_argument('out_dir', metavar='OUT_DIR')
    parser.add_argument('--img', action='store_true',
                        help='write images instead of .npy dumps')
    return parser


# no schema needed for deserialization
def iterplanes(avro_file):
    with open(avro_file, 'rb') as f:
        reader = AvroFileReader(f)
        for r in reader:
            yield BioImgPlane(r)


def main(argv):
    parser = make_parser()
    args = parser.parse_args(argv)
    try:
        os.makedirs(args.out_dir)
    except OSError as e:
        sys.exit('Cannot create output dir: %s' % e)
    for p in iterplanes(args.avro_file):
        pixels = p.get_xy()
        out_tag = '%s-z%04d-c%04d-t%04d' % (p.name, p.z, p.c, p.t)
        if args.img:
            # an image's X is an array's Y and vice versa
            pixels = pixels.reshape(pixels.shape[1], pixels.shape[0])
            out_fn = os.path.join(args.out_dir, '%s.tif' % out_tag)
            with closing(TIFF.open(out_fn, mode="w")) as fo:
                fo.write_image(pixels)
        else:
            out_fn = os.path.join(args.out_dir, '%s.npy' % out_tag)
            np.save(out_fn, pixels)


if __name__ == '__main__':
    main(sys.argv[1:])
