#!/bin/bash

set -eu

die() {
    echo "$1" 1>&2
    exit 1
}

minargs=2
if [ $# -lt ${minargs} ]; then
    die "Usage: $0 DFS_INPUT DFS_OUTPUT [LINES_PER_MAP]"
fi
DFS_INPUT=$1
MR_OUTPUT=$2
if [ $# -gt ${minargs} ]; then
    LINES_PER_MAP=$3
else
    LINES_PER_MAP=1
fi

SCRIPTS_DIR=$(cd "$(dirname "${BASH_SOURCE[0]}")"; pwd; cd - >/dev/null)
REPO_ROOT=$(dirname "${SCRIPTS_DIR}")
PKG=( "${REPO_ROOT}"/target/pydoop-features-*.jar )
if [ ! -e ${PKG[0]} ]; then
    pushd "${REPO_ROOT}"
    mvn clean compile assembly:single
    popd
    PKG=( "${REPO_ROOT}"/target/pydoop-features-*.jar )
fi
FEATURES_JAR=${PKG[0]}

hdfs dfs -rm -r -f "${MR_OUTPUT}"
hadoop jar ${FEATURES_JAR} it.crs4.features.GetMeta \
    -D mapreduce.input.lineinputformat.linespermap="${LINES_PER_MAP}" \
    "${DFS_INPUT}" "${MR_OUTPUT}"
