#!/bin/bash

# run "mvn package" in main project dir to build FEATURES_JAR
# NOTE: PLANES_PER_MAP must be a multiple of the image set size

die() {
    echo $1 1>&2
    exit 1
}

minargs=3
if [ $# -lt ${minargs} ]; then
    die "Usage: $0 INPUT OUTPUT PIPELINE [PLANES_PER_MAP]"
fi
INPUT=$1
OUTPUT=$2
PIPELINE_FN=$3
PIPELINE_BN=$(basename "${PIPELINE_FN}")
PLANES_PER_MAP=$4
[ -z "${PLANES_PER_MAP}" ] && PLANES_PER_MAP=0  # entire series
# TODO: add support for metadata file, as in run_features

FEATURES_JAR=../target/pydoop-features-1.0-SNAPSHOT.jar
BF_JAR=/home/${USER}/.m2/repository/ome/bioformats_package/5.1.0-HDFS/bioformats_package-5.1.0-HDFS.jar
MODULE=cell_profiler_example
MPY=${MODULE}.py
JOBNAME=${MODULE}-job
LOGLEVEL=DEBUG
MRV="--mrv2"
INPUT_FORMAT=it.crs4.features.BioImgInputFormat


pydoop submit \
    -D it.crs4.features.cppipe="${PIPELINE_BN}" \
    -D it.crs4.features.planespermap="${PLANES_PER_MAP}" \
    --upload-file-to-cache "${PIPELINE_FN}" \
    --upload-file-to-cache bioimg.py \
    --upload-file-to-cache ${MPY} \
    --num-reducers 0 \
    --input-format ${INPUT_FORMAT} \
    --avro-input v \
    --libjars ${FEATURES_JAR},${BF_JAR} \
    --log-level ${LOGLEVEL} ${MRV} \
    --job-name ${JOBNAME} \
    ${MODULE} ${INPUT} ${OUTPUT}
