#!/bin/bash

set -eu

die() {
    echo "$1" 1>&2
    exit 1
}

nargs=2
if [ $# -ne $nargs ]; then
    die "Usage: $0 DFS_INPUT DFS_OUTPUT"
fi
DFS_INPUT=$1
OUTPUT=$2
MR_OUTPUT=$2_metadata

SCRIPTS_DIR=$(cd "$(dirname "${BASH_SOURCE[0]}")"; pwd; cd - >/dev/null)
REPO_ROOT=$(dirname "${SCRIPTS_DIR}")
PKG=( "${REPO_ROOT}"/target/pydoop-features-*.jar )
if [ ! -e ${PKG[0]} ]; then
    pushd "${REPO_ROOT}"
    mvn clean compile assembly:single
    popd
    PKG=( "${REPO_ROOT}"/target/pydoop-features-*.jar )
fi
FEATURES_JAR=${PKG[0]}

MODULE=try_input_format
MPY=${MODULE}.py
JOBNAME=${MODULE}-job
LOGLEVEL=DEBUG
MRV="--mrv2"
INPUT_FORMAT=it.crs4.features.BioImgInputFormat


hdfs dfs -rm -r -f "${MR_OUTPUT}"
pydoop submit \
    -D bioimg.dump.dir="${OUTPUT}" \
    --upload-file-to-cache ${MPY} \
    --num-reducers 0 \
    --input-format ${INPUT_FORMAT} \
    --avro-input v \
    --libjars ${FEATURES_JAR} \
    --log-level ${LOGLEVEL} ${MRV} \
    --job-name ${JOBNAME} \
    ${MODULE} "${DFS_INPUT}" "${MR_OUTPUT}"
