#!/bin/bash

set -eu

SCRIPTS_DIR=$(cd "$(dirname "${BASH_SOURCE[0]}")"; pwd; cd - >/dev/null)
REPO_ROOT=$(dirname "${SCRIPTS_DIR}")
PKG=( "${REPO_ROOT}"/target/pydoop-features-*.jar )
if [ ! -e ${PKG[0]} ]; then
    pushd "${REPO_ROOT}"
    mvn clean compile assembly:single
    popd
    PKG=( "${REPO_ROOT}"/target/pydoop-features-*.jar )
fi

java -cp "${PKG[0]}" it.crs4.features.ImageToAvro "$@"
