#!/bin/bash

if [ "$#" == 0 ]; then
    echo "USAGE: ./$(basename $0) IMG_FILE"
    exit 2
fi

BASEDIR=$(cd $(dirname ${BASH_SOURCE[0]}); pwd; cd - >/dev/null)
pushd ${BASEDIR}/..
mvn exec:exec -Dexec.executable="java" -Dexec.args="-cp %classpath it.crs4.features.App $@"
popd
