#!/usr/bin/env python

import os
import numpy as np

import pydoop.hdfs as hdfs
import pydoop.utils as utils


N_ARRAYS = 4
SHAPE = (4, 5)
PYDOOP_EXE = os.path.join(os.path.expanduser('~'), '.local', 'bin', 'pydoop')


def main():
    in_dir, mr_in, out_dir, mr_out = [
        utils.make_random_str() for _ in xrange(4)
        ]
    print 'Image input dir:', in_dir
    print 'MapReduce input file:', mr_in
    with hdfs.open(mr_in, 'w') as mrf:
        for i in xrange(N_ARRAYS):
            path = hdfs.path.join(in_dir, 'a%d.npy' % (i+1))
            with hdfs.open(path, 'w') as fo:
                np.save(fo, np.random.random(SHAPE))
                mrf.write('%s\n' % fo.name)
    opts = '--num-reducers=0 -D mapred.map.tasks=2 -D out.dir=%s' % out_dir
    cmd = '%s script %s features.py %s %s' % (PYDOOP_EXE, opts, mr_in, mr_out)
    print 'Running %r' % (cmd,)
    os.system(cmd)


if __name__ == '__main__':
    main()
