#!/usr/bin/env python

# FIXME: not an integration test, move elsewhere

import sys
import csv
import argparse

import matplotlib.pyplot as plt


def get_data(fn):
    with open(fn) as f:
        data = {"shapes": [], "t": [], "err": []}
        reader = csv.DictReader(f, delimiter="\t")
        for r in reader:
            data["shapes"].append("%s x %s" % (r["W"], r["H"]))
            data["t"].append(float(r["ELAPSED_T"]))
            data["err"].append(float(r["ERROR"]))
    return data


def plot_data(data, img_fn):
    xlabels = data["shapes"]
    x = range(len(xlabels))
    plt.plot(x, data["t"])
    ymin, ymax = plt.ylim()
    plt.ylim((0, ymax))
    plt.xticks(x, xlabels)
    plt.xlabel("tile shape")
    plt.ylabel("total running time (s)")
    plt.savefig(img_fn, dpi=300)


def make_parser():
    parser = argparse.ArgumentParser()
    parser.add_argument("stats_fn", metavar="STATS_FILE",
                        help="stats file (from run_tile_size)")
    parser.add_argument("-o", "--out-fn", metavar="FILE", default="stats.png",
                        help="output filename")
    return parser


def main(argv):
    parser = make_parser()
    args = parser.parse_args(argv)
    plot_data(get_data(args.stats_fn), args.out_fn)


if __name__ == '__main__':
    main(sys.argv[1:])
