#!/usr/bin/env python

import os
import subprocess as sp
import tempfile
from itertools import izip

from wndcharm.FeatureVector import FeatureVector

import pyfeatures.pyavroc_emu as pyavroc_emu
from pyfeatures.feature_names import FEATURE_NAMES


THIS_DIR = os.path.dirname(os.path.abspath(__file__))
IMG_FN = os.path.join(THIS_DIR, "37117_small.tif")


def run_serialize(img_fn, out_dir):
    args = ["pyfeatures", "serialize", "-o", out_dir, img_fn]
    sp.check_call(args)


def run_deserialize(avro_fn, out_dir, img=True):
    args = ["pyfeatures", "deserialize", "--img", avro_fn, out_dir]
    sp.check_call(args)


def run_feature_calc(avro_fn, out_dir, long=False, w=None, h=None):
    args = ["pyfeatures", "calc", "-o", out_dir, avro_fn]
    if long:
        args.append("-l")
    if w is not None:
        args.extend("-W", int(w))
    if h is not None:
        args.extend("-H", int(h))
    sp.check_call(args)


def check_features(img_fn, avro_out_fn, long=False):
    sigs = FeatureVector(source_filepath=img_fn, long=long)
    sigs.GenerateFeatures(write_to_disk=False)
    fmap = dict(izip(sigs.feature_names, sigs.values))
    with open(avro_out_fn) as f:
        records = [_ for _ in pyavroc_emu.AvroFileReader(f)]
    assert len(records) == 1
    rec = records[0]
    for fname, (vname, idx) in FEATURE_NAMES.iteritems():
        v = fmap.get(fname)
        if v is None:
            assert not long
            assert len(rec[vname]) == 0
        else:
            assert abs(rec[vname][idx] - v) <= 1e-7


def main():
    wd = tempfile.mkdtemp(prefix="pyfeatures_")
    print "working dir: %r" % (wd,)
    avro_input_dir = os.path.join(wd, "avro_in")
    avro_output_dir = os.path.join(wd, "avro_out")
    img_output_dir = os.path.join(wd, "planes")
    run_serialize(IMG_FN, avro_input_dir)
    basenames = os.listdir(avro_input_dir)
    assert len(basenames) > 0
    for bn in basenames:
        fn = os.path.join(avro_input_dir, bn)
        run_deserialize(fn, img_output_dir)  # for visual inspection
        run_feature_calc(fn, avro_output_dir)
        out_bn = "_features".join(os.path.splitext(bn))
        out_fn = os.path.join(avro_output_dir, out_bn)
        assert os.path.isfile(out_fn)
        check_features(IMG_FN, out_fn)


if __name__ == "__main__":
    main()
